add missing - in docker tags
the docker tags are alll in the format of fXX-docker, the mapping
from the fxx to fxx-docker branches to tags was missing the -
so add it it prevents an error like:
__koji__compose_koji.GenericError: No such entry in table tag: f26docker

Signed-off-by: Dennis Gilmore <dennis@ausil.us>