mail-templates: Update for Fedora Linux instead of Fedora, spellings
Main change:

Fedora is a community; Fedora Linux is our OS.
https://communityblog.fedoraproject.org/fedora-is-a-community-fedora-linux-is-our-os/

Thus we should use "Fedora Linux N" instead of "Fedora N".

Additional changes:

- use YYYY-MM-DD for all date values.
  Exception: 05-beta-release uses "end of MONTH".

- use fN as the designator for the Fedora Linux release number.
  Note: Many URLs are now f-fN, which needs to be replaced to f-37

- Add a space before inline cross references.
  This was inconsistent: sometimes [1] and sometimes[2].

- References start with [1] and not with [0]

- Fix two instances of incorrect capitalization
  ("fedora repository" instead of "Fedora repository" and
  "fedora Project wiki" instead of "Fedora Project wiki").

- Except for lines with URL, linit line length to 72 characters.

Signed-off-by: Manfred Spraul <manfred@colorfullife.com>